### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by fredroo** [rexos/wordlist#18]
How to generate 5 digits like this with 4 digits as prefix @rexos 
example 9996[0-9]

output required:
99960
99961
99962
until 99969

**Comment by rexos** [comment]
Hello!
The following command (within python prompt) should output what you ask for:

import wordlist
generator = wordlist.Generator('0-9')
for each in generator.generate_with_pattern('9996@'):
    print(each)

You can also use it from command-line, please check out the project description.
Regards

**Comment by fredroo** [comment]
thanksk a lot, i ask command line with pattern but that way solve, only create py file and run this, thanks a lot for your fast reply

**Comment by fredroo** [comment]
this example of command line solved my problems

wordlist [charset] @@q@@er@t@y
example of use in my case
wordlist [0-9] 32@@ >> numbers-prefix-phone-digits.txt
wordlist [0-9] 33@@ >> numbers-prefix-phone-digits.txt
wordlist [0-9] 34@@ >> numbers-prefix-phone-digits.txt
wordlist [0-9] 35@@ >> numbers-prefix-phone-digits.txt

**Comment by fredroo** [comment]
@rexos
wordlist [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!#$%&'*+-/=?^_`{|}~.] -m 1 -M 1 > wordlist.txt

why this charsets not result with output, some char is invalid? how to fix to generate this wordlist
